# Generated by Django 5.1 on 2024-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=80)),
                ('patient_description', models.TextField()),
                ('patient_phone_number', models.CharField(max_length=25)),
                ('appointment_date_and_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Прийом',
                'verbose_name_plural': 'Прийоми',
            },
        ),
    ]
