# Generated by Django 5.1 on 2024-08-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointments',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_appointment', to='appointments.doctor'),
            preserve_default=False,
        ),
    ]
