# Generated by Django 5.1 on 2024-08-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_doctor_appointments_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_photo',
        ),
    ]
